name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - name: build cms-api
        run: pnpm build
        working-directory: apps/cms-api

      - name: build cms-admin
        run: pnpm build
        working-directory: apps/cms-admin

      - name: build cms-page-builder
        run: pnpm build
        working-directory: apps/cms-page-builder
