name: test-api

on:
  push:
    paths-ignore:
      - apps/cms-admin
      - apps/cms-page-builder
      - '**.md'
  pull_request:
    paths-ignore:
      - apps/cms-admin
      - apps/cms-page-builder
      - '**.md'

env:
  CI: true

jobs:
  api-unit-test:
    name: 'Unit test: cms-api'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm type-check
        working-directory: apps/cms-api

      - run: pnpm lint
        working-directory: apps/cms-api

      - run: pnpm test:unit --coverage
        working-directory: apps/cms-api

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit-test

  integration-test:
    name: 'Integration test: cms-api'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm test:integration --coverage
        working-directory: apps/cms-api

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration-test
